baseURL = 'https://theeverythingjournal.netlify.app'
languageCode = 'en-us'
title = 'The Everything Journal'
description = 'Welcome to a place where stories come to life through words, and moments that matter.'
author = 'lyskhea'
theme = 'quint'
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "G-5238SP6F"

[pagination]
pagerSize = 6

[imaging]
quality = 80  # Reduce image quality to 80 (good balance)

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  posts = "/:slug/"

[minify]
  disableXML = true
  minifyOutput = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100

[[related.indices]]
  name = "categories"
  weight = 80

[params]
disableKinds = ["taxonomy", "term"] # Make sure "robotsTXT" is NOT listed here
css = ["css/custom.css"]
numImages = 30
useToc = true

contact = "You can write me an [email](mailto:me)."

[[params.social]]
    url = "https://github.com/lyskh"
    icon = "/social/github.svg"
    name = "GitHub"

[[params.social]]
  url = "https://www.facebook.com/people/The-Everything-Journal/61574084311303/"
  icon = "/social/facebook.svg"
  name = "Facebook"

[[params.social]]
  url = "https://instagram.com/theeverythingjournal_lyskhea/"
  icon = "/social/instagram.svg"
  name = "Instagram"
